ID: kallisto-test-20210811
samples: /data/exploratory/Users/jasmine.alvarez/orpheus/resources/sample_sheet.new.tsv
organism: "Human"
ref:
    fa: /data/exploratory/Users/jasmine.alvarez/test/transcripts.fasta.gz
    gtf: /data/exploratory/Users/jasmine.alvarez/test/transcripts.gtf.gz
    build: Human_hg38
    known_sites: ""
outpath: /data/exploratory/Users/jasmine.alvarez/orpheus/outs
aligner: kallisto
skip_trimming: False
