ID: 2020_10_22_test
Title: "2020-10-22 Test"
HPC_ID: jeff.alvarez
Contact_name: "Jeff Alvarez"
Organism: "Human"
fastqs: /data/exploratory/Users/jeff.alvarez/orpheus/data/samples/
samples: /data/exploratory/Users/jeff.alvarez/orpheus/data/sample_sheet.tsv
ref:
        fa: /data/exploratory/Users/jeff.alvarez/orpheus/data/Human_B37.3_chr1.fasta
        gtf: /data/exploratory/Users/jeff.alvarez/orpheus/data/Human_B37.3_chr1.gtf
        build: Human_B37.3
trimming:
        skip: false
known_sites: /data/exploratory/Users/jeff.alvarez/pipeline_ins/dbsnp_138.b37.chr_1.vcf.gz
call_variants: True
